### ISSUE TITLE
Zipkin UI AWS ElasticSearch Encrypted data

### ISSUE THREAD

**Issue by jhonatanforero** [openzipkin/docker-zipkin-aws#7]
Hi @adriancole 

This is more a new feature, we have an elasticsearch as aws service and a zipkin docker as kinesis collector, for security concerns we need all data encrypted in elasticsearch, is possible zipkin UI Decrypt the data with a public key kms aws? I think this is a possible new feature

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/encryption-at-rest.html

**Comment by devinsba** [comment]
When Amazon says something is encrypted at rest that means that the APIs you use to interact with those things do not have to worry about decrypting the data. In this case it means the ElasticSearch instances the AWS hosts for you write their files to disk encrypted.

**Comment by jhonatanforero** [comment]
HIi @devinsba 

Ok, but exists something for decrypt data with zipkin UI if maybe the zipkin collectors encrypt the data  (new feature)? it's only a discussion.  the store storage will be Elasticsearch (Forget the url) think in **aws kms**  module some integration..

**Comment by devinsba** [comment]
If the collectors encrypted the data, then the UI could not query the data in any reasonable fashion. Please take any other requests or discussion about this to the zipkin repo: https://github.com/openzipkin/zipkin
